import re

def format(text, url):
    return format_for_linkedin(add_footer(text,url))
    


def format_for_linkedin(text):
    # Convert markdown headers (e.g. # Title) to bold
    text = re.sub(r'^#{1,6}\s*(.+)', r'**\1**', text, flags=re.MULTILINE)

    # Replace double asterisks around text with nothing (to remove bold marks already wrapped)
    text = re.sub(r'\*\*(.*?)\*\*', r'\1', text)

    # Remove single asterisk emphasis (e.g. *word*)
    text = re.sub(r'\*(.*?)\*', r'\1', text)

    # Clean extra whitespace
    return text.strip()

def add_footer(summary, article_url):
    footer = f"""\n\n—
    Original article: {article_url}  
    Generated by my bot 🤖 → [GitHub](ADD YOUR REPO)"""
    return summary + footer